### PR TITLE
Branch

### PR DESCRIPTION
**Pull request by vignesho**
EDWORKS IS AN EDUCATIONAL WEBSITE WHICH PROVIDES JOB OPPORTUNITIES, COURSES, MENTORSHIPS AND OTHER LEARNING OPPORTUNITIES THAT LETS YOU UPGRADE YOUR SKILLS TO THE NEXT LEVEL.

### CODE REVIEW

**Review by surendrasinghs — CHANGES_REQUESTED** [review]
Hey team, thank you for your submission. Please use the template that was provided and do not delete the "skill-a-thon-1.0-submissions.md" file. Kindly make a copy of the file, modify it with your details, and re-submit the PR. Thanks!

**Review by vignesho — COMMENTED** [review]
sir we have created the said changes and have committed to the branch sir.

**Review by vignesho — COMMENTED** [review]
Required changes have been done sir. Thank you for updating us about it. 
Kindly inform us if there are any more changes required.

[skill-a-thon-1.0-submissions.md](https://github.com/skill-a-thon/.github/files/10836304/skill-a-thon-1.0-submissions.md)

**Comment by vignesho** [comment]
said changes have been made sir.

**Comment by vignesho** [comment]
Said Changes have been made Sir.

**Comment by ravi-prakash-v** [comment]
Hi Team, please provide links to your source code in the submissions link provided in the submission.md template file. Do not check-in your code as part of your submissions. Closing this PR for now.

**Pull request closed without merging**
