### PR TITLE
abi1562004_4435

### PR DESCRIPTION
**Pull request by curiouscoders07**

### CODE REVIEW

**Comment by curiouscoders07** [comment]
We are team abi1562004_4435 
We loved doing this project thank you for this opportunity
github repository : https://github.com/curiouscoders07/skill-a-thon_submission
Host link: https://youtu.be/kCBBjksHub4

**Review by surendrasinghs — CHANGES_REQUESTED** [review]
Hey team, thank you for your submission. Please use the template that was provided and do not delete the "skill-a-thon-1.0-submissions.md" file. Kindly make a copy of the file, modify it with your details, and re-submit the PR. Thanks!

**Comment by curiouscoders07** [comment]
We have updated the file according to the template provided, Thank you

**Review by surendrasinghs — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
