### PR TITLE
Team Innovators (Challenge-3)

### PR DESCRIPTION
**Pull request by amarts**
| Team Name | Team members | Challenge Number | Product version | 
|--|--|--|--|
| Innovator | Giriraj Daga (Affinidi), Prashant M (Dhiway), Vikas J (BetterPlace), Denzil Lewis (Hacker Earth), Neeraj Sharma (SunStone) | 3 | 0.0.1 |

All details in the added .md file.

### CODE REVIEW

**Comment by amarts** [comment]
While the project works, we are still working on some integrations and video recording of demo. Once complete will update the links in this PR (before 9:30am). So, would be great if this is merged around the time of 9:30am.

Thanks.

**Comment by amarts** [comment]
For those checking this PR, the product demo link is @ [GoogleDrive](https://drive.google.com/file/d/1AM4nn7hBxRq-B9_B7QoWYirDS2g6zZb3/view?usp=sharing)

**Review by ravi-prakash-v — CHANGES_REQUESTED** [review]
Hey team, thank you for your submission. Can you please submit your details as per the instructions mentioned in https://github.com/skill-a-thon

Thanks!

**Comment by amarts** [comment]
Sure. On it, I should have it done in the next 15mins.

**Comment by amarts** [comment]
addressed the requested changes.

**Review by ravi-prakash-v — APPROVED** [review]
Approved

**Pull request merged**
