### PR TITLE
studday infinity

### PR DESCRIPTION
**Pull request by NARESHRAJ701**
I am writing this message to express my sincere gratitude for organizing the skillathon. It was an incredibly well-planned and executed event, and I am truly grateful for the opportunity to have participated.

This skillathon was an amazing experience that challenged me to think outside the box and collaborate with other like-minded individuals. I appreciated the effort that you and your team put into ensuring that all participants were well taken care of and had everything they needed to be successful. The venue, refreshments, and technical support were all top-notch, and I felt very comfortable throughout the entire event.
Once again, thank you for organizing such an amazing event. I appreciate all the time and effort that you put into making it a success. I look forward to participating in future events and hope to have the opportunity to work with you again.

Best regards,
team sun star moon

### CODE REVIEW

**Comment by NARESHRAJ701** [comment]
we have reuploaded submission .md file again please consider our request and review our pull request.

**Review by NARESHRAJ701 — COMMENTED** [review]
we have reuploaded submission .md file again please consider our request and review our pull request.

**Review by surendrasinghs — CHANGES_REQUESTED** [review]
Hey team, thank you for your submission. Please use the template that was provided and do not delete the "skill-a-thon-1.0-submissions.md" file. Kindly make a copy of the file, modify it with your details, and re-submit the PR. Check https://github.com/skill-a-thon.
Thanks!

**Comment by ravi-prakash-v** [comment]
Hi Team, closing this PR as multiple files have been checked in.

**Pull request closed without merging**
