### PR TITLE
Arise Challenge 4

### PR DESCRIPTION
**Pull request by ajaybhatt17**

### CODE REVIEW

**Comment by ravi-prakash-v** [comment]
Hey team, thank you for your submission. Please use the template that was provided and do not delete the "skill-a-thon-1.0-submissions.md" file. 

Kindly follow the steps mentioned here: https://github.com/skill-a-thon and resubmit the PR.

**Review by ravi-prakash-v — CHANGES_REQUESTED** [review]
Hey team, thank you for your submission. Please use the template that was provided and do not delete the "skill-a-thon-1.0-submissions.md" file. Kindly make a copy of the file, modify it with your details, and re-submit the PR. Thanks!

Kindly do not submit your codebase in the PR. There are specific fields in the PR that point to the submission in your own GitHub repository.

Kindly follow the steps mentioned here: https://github.com/skill-a-thon

**Review by surendrasinghs — APPROVED** [review]
Looks good, thank you!

**Comment by ravi-prakash-v** [comment]
Hi Team, Please edit the file name as per the standard procedure mentioned here https://github.com/skill-a-thon , and resubmit.

**Pull request closed without merging**
